### ISSUE TITLE
Some tests do not recognize the destroy flag

### ISSUE THREAD

**Issue by aganesh-suse** [rancher/distros-test-framework#112]
Restartservice test does not recognize the destroy flag. 
There may be other tests that do not recognize this flag as well. 
We should check all the test suites to ensure that this flag is recognized.

**Comment by fmoral2** [comment]
done here 
https://github.com/rancher/distros-test-framework/pull/102/files#diff-9c261f8fc50b0ecd105330bfd02e8ae8b919ff371c57754897c494d58e859dd3
