### ISSUE TITLE
Changes in build.sh causing errors Jenkins build

### ISSUE THREAD

**Issue by mdrahman-suse** [rancher/distros-test-framework#27]
Jenkins build is broken due to a recent change got merged: [11cc573](https://github.com/rancher/distros-test-framework/commit/11cc5731c96c84b623cd9ca4420345e9bad383c5)

Seeing error below in console logs
```
+ BUILD=docker
 + build . -f scripts/Dockerfile.build -t acceptance-tests-rke2_validate_cluster291
 ./scripts/build.sh: line 17: build: command not found
```
This is currently blocking the job builds

Possible solution suggested by @ShylajaDevadiga 

> We could avoid variable here and get the exit status from command https://github.com/rancher/distros-test-framework/blob/main/scripts/build.sh#L17C23-L17C23

**Comment by fmoral2** [comment]
https://github.com/rancher/distros-test-framework/pull/28
