### ISSUE TITLE
Update functions to use newer cluster info retrieval method

### ISSUE THREAD

**Issue by rancher-max** [rancher/distros-test-framework#73]
This is introduced in the DualStack PR. Ref: https://github.com/rancher/distros-test-framework/pull/66#discussion_r1475210470

**Comment by fmoral2** [comment]
lets wait to introduce this , after => https://github.com/rancher/qa-tasks/issues/1069 
which will probably change the way or already refactor the way this injection is built

**Comment by fmoral2** [comment]
https://github.com/rancher/distros-test-framework/pull/79
